name: Running npm tests
on: push
jobs:
    Running_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: echo "Hello this is your first workflow"
            - name: Get code
              uses: actions/checkout@v3
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
